In [ ]:
import numpy as np

np.array()

In [3]:
arr = np.array([1,2,3,4,5])
print("array:", arr)

array: [1 2 3 4 5]


np.zeros()

In [4]:
arr_zeros = np.zeros((3,4))
print("arr_zroes[]:",arr_zeros)

arr_zroes[]: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


np.ones()

In [5]:
arr_ones = np.ones((2,3))
print("arr_ones[]:", arr_ones)

arr_ones[]: [[1. 1. 1.]
 [1. 1. 1.]]


np.reshape()

In [6]:
reshaped_arr = np.reshape(arr,(5,1))
print("reshaped arr:", reshaped_arr)

reshaped arr: [[1]
 [2]
 [3]
 [4]
 [5]]


np.concatenate()

In [7]:
concatenated_arr = np.concatenate((arr,arr))
print("concatenated:", concatenated_arr)

concatenated: [1 2 3 4 5 1 2 3 4 5]


np.mean()

In [8]:
mean_value = np.mean(arr)
print("mean:" , mean_value)

mean: 3.0


np.sum()

In [9]:
sum_value = np.sum(arr)
print("sum:", sum_value)

sum: 15


np.min()

In [10]:
min_value = np.min(arr)
print("min:", min_value)

min 1


np.max()

In [11]:
max_value = np.max(arr)
print("max:", max_value)

max: 5


np.argmin()

In [13]:
argmin_value = np.argmin(arr)
print("argmin:", argmin_value)

argmin: 0


np.argmax()

In [14]:
argmax_value = np.argmax(arr)
print("argmax:", argmax_value)

argmax: 4


np.random.rand()

In [15]:
rand_arr = np.random.rand(3,3)
print("ranodom arr", rand_arr)

ranodom arr [[0.33243869 0.16647653 0.60750776]
 [0.08839597 0.06935348 0.43074075]
 [0.54382086 0.11785977 0.89513139]]


np.random.randn()

In [16]:
randn_arr = np.random.randn(2,2)
print("randn arr", randn_arr)

randn arr [[ 0.60813682  1.04883659]
 [-0.42735013  0.41732091]]


np.random.randint()

In [17]:
randint_arr = np.random.randint(1,10, size=(2,2))
print("random int arr (with range [1,10] and size 2x2)", randint_arr)

random int arr (with range [1,10] and size 2x2) [[8 6]
 [1 2]]


np.dot()

In [20]:
dot_product = np.dot(arr,arr)
print("dotProduct:", dot_product)

dotProduct: 55
